### ISSUE TITLE
Allow unlimited length in options

### ISSUE THREAD

**Issue by samnabi** [Addpixel/KirbyComments#10]
It would be helpful to allow unlimited length for the plugin options. `max-character-count` in particular would benefit from a `false` option to allow unlimited length of comments.

**Comment by florianpircher** [comment]
I don’t know why anyone would want someone been able to paste “Alice in Wonderland” into a comment, but as long as it is not the default option (which it will never be) I am OK with it. Maybe the plugin gets used in ways I could never imagine, so I think this is a acceptable addition to the plugin’s feature set.

**Comment by samnabi** [comment]
It's difficult to decide what a maximum length should be, so I just put 999999999 or something in my config. It's not the end of the world, but I realized the arbitrarily large number is kind of silly.

**Comment by florianpircher** [comment]
As a good default I would suggest something between 512 and 2048. You typically don’t want people (nor bots) to be able to paste books or the first 10^6 digits of π into the comments field. As mentioned above, maybe some developers want to use the plugin for non-comment purposes, where it is fine to not set a limit, so I will add this option in version 1.1.7.

**Comment by florianpircher** [comment]
After thinking more about this I changed my mind. `max-character-count` is an integer option and allowing booleans would introduce to much complexity, especially because [booleans are handled like integers in PHP](http://php.net/manual/en/language.types.integer.php#language.types.integer.casting.from-boolean). So `false` would evaluate to **0 characters** *and* **infinitely many characters**. I would suggest using [`PHP_INT_MAX`](http://php.net/manual/en/reserved.constants.php#constant.php-int-max) as value for `max-character-count` if you can’t decide on a maximum character count.

**Comment by samnabi** [comment]
Thanks for the `PHP_INT_MAX` tip, that feels right to me.
