### ISSUE TITLE
Pagination support?

### ISSUE THREAD

**Issue by jenstornell** [Addpixel/KirbyComments#16]
I just found this plugin again and it really looks to be well maintained. As far as I can see on the demo page there is no pagination for a page with many comments? Is it a feature that you would like to implement?

Personally I don't care about page numbers, just next/previous page would be fine. Else the page would take long to load, the search engines would see more comments than the article text etc.

**Comment by florianpircher** [comment]
The demo page uses no pagination because I want to show off with the many people how are using my plugin 😉. There comments are listed by the default comments snippet, but you can write your own snippet and add lots of fun and interesting features to it, such as pagination.

I don’t think this is a common use-case and as the default snippet serves as reference for creating your own snippet, I try to keep it simple. The default snippet lacks a lot of features, such as language support, date-format customisation, no AJAX loading or custom error messages, all of which would bloat the default snippet and make it unusable for reference.

The plugin itself ships with a snippet and I try to make it as good as it can be. If you want to build on-top of it, have a look at the [Custom Markup](https://github.com/Addpixel/KirbyComments#custom-markup) and the [API Documentation](https://github.com/Addpixel/KirbyComments#api-documentation) sections in the readme file.

**Comment by jenstornell** [comment]
Alright. It should be quite simple to implement myself with a route or get variables then. I close this because of the "wontimplement" label. =)
