### ISSUE TITLE
Blueprints as yml

### ISSUE THREAD

**Issue by jenstornell** [Addpixel/KirbyComments#18]
In the future the `php` extension might be used differently by Kirby. Blueprint as `yml` gives better colors in most code editors.

**Comment by florianpircher** [comment]
Why do you think `.php` files could be used differently in the future by Kirby? I think I just copied and modifies blueprints from the starterkit and I think the were `.php` files. I just checked, currently the starterkit [uses `.yml` files](https://github.com/getkirby/starterkit/tree/master/site/blueprints). Without explaining the change, the commit [fba71d12ab9d30347b9ca12704edeb4b3af970bc](https://github.com/getkirby/starterkit/commit/fba71d12ab9d30347b9ca12704edeb4b3af970bc#diff-db626c8394b217cae26baf794fb7c434) of the starterkit renamed and modifies `.php` to `.yml` files.

I will change to `.yml`, just as the starterkit did, but I am still unsure about why.

(Maybe it’s just because of the better syntax highlighting.)

**Comment by jenstornell** [comment]
It's not set in stone. It's just a "maybe" but I think that `yml` is more correct for the yaml language anyway.

https://github.com/getkirby/panel/issues/979

@lukasbestle

>Maybe we should just kill backwards-compatibility here.
>I agree that it's better to remove that old behavior to keep this clean.

The reason for this change would be to use `php` for blueprints with logic.

Until we know about the change, you can apply the change in order to save two rows in the file and get better syntax highlighting.

**Comment by florianpircher** [comment]
This is interesting! Logic in blueprints is something I always wanted for *Kirby Comments*. As long as getkirby/panel/issues/979 is not resolved I’ll be switching to YAML.
