### ISSUE TITLE
Thanks 👏 & Use Git-Commit-And-Push-Content Plugin with a Hook

### ISSUE THREAD

**Issue by wottpal** [Addpixel/KirbyComments#38]
Just a little thank you for the ongoing efforts you put into this nice plugin. I am using it on my new personal site (e.g. [here](https://wottpal.com/items/my-kirby-plugins))! Transition to 1.5 was smooth and I will try out some things with Custom Fields & Nested Comments in the future. 

I already re-implemented pushing to my remote repository (with the [gcap-plugin](https://github.com/blankogmbh/kirby-git-commit-and-push-content)) with one of the new **Hooks**. I just wanted to post my solution here if anyone else is in need for this:

```php
c::set([
  'comments.hooks.did-save-comment' => function ($comments, $comment, $commentPage) {
    $should_commit = c::get('gcapc-commit', false);
    $should_push = c::get('gcapc-push', false);
    if ($should_commit && $should_push) {
      $gitHelper = new KirbyGitHelper();
      $gitHelper->kirbyChange("commented on ".$commentPage->uri());
    }
  }
]);
``` 

One thing which could be improved though is the loading time. After somebody made a comment it gets pushed & commented synchronously which definitely slows down the page-load. Any idea here? Maybe I should use something like [Kirby Queue](https://github.com/sebsel/queue-for-kirby) by @sebsel...

Happy Halloween 🎃🧛‍♂️🧟‍♂️

**Comment by florianpircher** [comment]
This is a great use for hooks, thanks for sharing! I think you want to change this line:

```php
$gitHelper->kirbyChange("commented on ".$commentPage->uri());
```

to this:

```php
$gitHelper->kirbyChange("commented on ".$comment->page()->uri());
```

This shows the difference between [`$commentPage`](https://github.com/Addpixel/KirbyComments#did-save-commentcomments--comments-comment--comment-commentpage--page) and [`$comment->page()`](https://github.com/Addpixel/KirbyComments#comment-page--page):

```
content/
└─ blog/
   └─ 1-hello-world/        <-  $comment->page()
      ├─ post.txt
      └─ comments/
         ├─ comments.txt
         ├─ 1-comment-1/    <-  $commentPage
         │  └─ comment.txt
         ├─ 2-comment-2/
         │  └─ comment.txt
         └─ 3-comment-3/
            └─ comment.txt
```

Not blocking the page load sounds like a good idea but I don’t know if this can be done with *Queue for Kirby* as I have never used it.

I have to close this issue because it isn’t actionable. I am planning to publish a cookbook for Kirby Comments (inspired by [Kirby’s cookbook](https://getkirby.com/docs/cookbook)) where I will include this snippet.

**Comment by wottpal** [comment]
Just for reference, after some minor issues I got everything working asynchronously with a queue and a cronjob. 🎉
I posted my solution here: https://github.com/sebsel/queue-for-kirby/issues/3#issuecomment-341974133.
