### ISSUE TITLE
Change email.template.txt without modifying the core one

### ISSUE THREAD

**Issue by malvese** [Addpixel/KirbyComments#5]
Is there a way to use a copy of this file, so it would not be overwritten when the plugin is updated?
Thanks

**Comment by florianpircher** [comment]
This is a very good point. I’ll see, what alternatives would be best. Suggestion are most welcome.

**Comment by malvese** [comment]
Perhaps making it a snippet? I was happy to see I could override `comments.php` by copying it in the right folder :)

**Comment by florianpircher** [comment]
Yes, the `comments.php` snippet serves as a production ready example usage of the Kirby Comments plugin, so users of the plugin are encouraged to use it as such an example and write their own comments form/list.

I’m still unsure about the correct method of storing the email template (snippet, template, page, configuration, …).

**Comment by florianpircher** [comment]
This is now fixed in [1.1.5](https://github.com/Addpixel/KirbyComments/releases/tag/1.1.5).

The best solution I found was declaring the email.template.txt file as plugin asset, so users can create alternative assets in assets/plugins/comments/. Instructions on how to customise the email-body-template file can be found in the [README](https://github.com/Addpixel/KirbyComments/tree/1.1.5#email-notifications). More about customising plugin assets in [the Kirby docs](https://getkirby.com/docs/developer-guide/plugins/assets#customizing-plugin-assets).
