### ISSUE TITLE
Why does comments.txt have a date?

### ISSUE THREAD

**Issue by samnabi** [Addpixel/KirbyComments#8]
I can't seem to figure out where the `comments.txt` date field is used. Why do we need this variable?

**Comment by florianpircher** [comment]
As described in [README#file-structure](https://github.com/Addpixel/KirbyComments#file-structure), KirbyComments does not ship with a template for `comments.txt` files. Because of that those pages are not styles nor reachable by clicking internal links. However, developers are free to make `comments.txt` a publicly accessible page.

For that reason, a creation date is stored alongside the comments page. It does not wast a lot of space and is useful for creating a pages dedicated to listing all comments of other pages. Personally, I don’t have strong feeling on whether to keep it or not.

To conclude:
- the date field is not used by the plugin
- we do not need it, it’s simply a convenience access to the creation date of the first comment
- it is redundant information and wastes space, but the impact is (I think) negligible
- I am happy to remove it, if any reasons for doing so are brought forth

**Comment by samnabi** [comment]
I have no strong opinions one way or the other. I'm just doing some debugging (imported a lot of comments from Disqus) and wanted to make sure to rule out this date field as a potential cause of bugs.
